# Running a Forward Pass and Exploring Model Capacity

## Step 1: Setting Up for the Forward Pass


In [ ]:
import torch
import torch.nn as nn

# Define a feedforward neural network
class SimpleFNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super().__init__()  # Use modern Python 3 super()
        self.layers = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, output_size)
        )

    def forward(self, x):
        return self.layers(x)

# Initialize model with specified input, hidden, and output sizes
# input_size: 4 features
# hidden_size: 10 neurons in the hidden layer
# output_size: 3 output units (e.g., for a 3-class classification)
model = SimpleFNN(input_size=4, hidden_size=10, output_size=3)
print("Model initialized:")
print(model)

Model initialized:
SimpleFNN(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=3, bias=True)
  )
)


## Step 2: Executing a Forward Pass


In [ ]:
# Sample input tensor: 1 sample, 4 features (matching input_size)
sample_input = torch.randn(1, 4)
print("\nSample Input Tensor:")
print(sample_input)

# Forward pass through the network
# This calls the model's forward() method
output = model(sample_input)
print("\nNetwork Output (from original model):")
print(output)


Sample Input Tensor:
tensor([[ 0.0914,  0.4003,  0.7525, -0.8251]])

Network Output (from original model):
tensor([[-0.4221,  0.1149, -0.2154]], grad_fn=<AddmmBackward0>)


## Step 3: Experimenting with Model Size


In [ ]:
# Redesigned model with a smaller hidden size (reduced capacity)
# hidden_size: 5 neurons (compared to 10 in the original model)
small_model = SimpleFNN(input_size=4, hidden_size=5, output_size=3)
print("\nSmall Model initialized:")
print(small_model)

# Forward pass with the small model using the same sample input
small_output = small_model(sample_input)
print("\nOutput from Small Model:")
print(small_output)

# Redesigned model with a larger hidden size (increased capacity)
# hidden_size: 50 neurons (compared to 10 in the original model)
large_model = SimpleFNN(input_size=4, hidden_size=50, output_size=3)
print("\nLarge Model initialized:")
print(large_model)

# Forward pass with the large model using the same sample input
large_output = large_model(sample_input)
print("\nOutput from Large Model:")
print(large_output)


Small Model initialized:
SimpleFNN(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=3, bias=True)
  )
)

Output from Small Model:
tensor([[-0.0476, -0.1830, -0.0185]], grad_fn=<AddmmBackward0>)

Large Model initialized:
SimpleFNN(
  (layers): Sequential(
    (0): Linear(in_features=4, out_features=50, bias=True)
    (1): ReLU()
    (2): Linear(in_features=50, out_features=3, bias=True)
  )
)

Output from Large Model:
tensor([[0.1210, 0.2458, 0.1149]], grad_fn=<AddmmBackward0>)
